# Generated by Django 4.2.7 on 2024-03-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
