# Generated by Django 4.2.7 on 2024-03-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
