# Generated by Django 4.2.7 on 2024-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(verbose_name='Euro Order Total'),
        ),
    ]
