# Generated by Django 4.2.7 on 2024-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_compare_compareitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
