# Generated by Django 4.2.7 on 2024-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_compareitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='primary_image',
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image1',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image2',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image3',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image4',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
