# Generated by Django 4.2.7 on 2024-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Showroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='glb_file',
            field=models.FileField(blank=True, upload_to='glb_files/'),
        ),
    ]
