# Generated by Django 4.2.7 on 2024-04-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_showroom_product_glb_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Showroom',
            new_name='showroom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glb_file',
        ),
    ]
