# Generated by Django 4.2.7 on 2024-04-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discreption',
        ),
    ]
